In [375]:
import pandas as pd
import numpy as np
import datetime
from sklearn.metrics import mean_squared_error
from math import sqrt

In [376]:
data=pd.read_csv("C:\Users\SAI SUPRAJA M\Documents\GitHub\HomeValuePrediction\data\preprocessed_data.csv", low_memory=False)

In [377]:
data.head()

lotsizesquarefeet  calculatedfinishedsquarefeet  bedroomcnt  bathroomcnt  \
0          -0.000798                     -0.000798         3.0          2.0   
1          -0.000626                     -0.000626         4.0          3.0   
2          -0.000822                     -0.000822         5.0          2.0   
3          -0.002115                     -0.002115         5.0          3.0   
4          -0.001085                     -0.001085         4.0          3.5   

   regionidzip  garagecarcnt  poolcnt  AgeofHouse  buildingclasstypeid  
0            0           2.0      0.0        41.0                  0.0  
1            1           1.0      0.0        67.0                  0.0  
2            2           1.0      0.0        66.0                  0.0  
3            3           2.0      0.0        47.0                  0.0  
4            4           2.0      0.0        56.0                  0.0

In [378]:
sample = [-0.001201,-0.001201,4.0,4.0,0,0.0,0.0,67.0,0.0]

In [379]:
data_array = data.values
data_array

array([[-7.98499406e-04, -7.98499406e-04,  3.00000000e+00, ...,
         0.00000000e+00,  4.10000000e+01,  0.00000000e+00],
       [-6.26203721e-04, -6.26203721e-04,  4.00000000e+00, ...,
         0.00000000e+00,  6.70000000e+01,  0.00000000e+00],
       [-8.22313798e-04, -8.22313798e-04,  5.00000000e+00, ...,
         0.00000000e+00,  6.60000000e+01,  0.00000000e+00],
       ...,
       [-4.79013568e-04, -4.79013568e-04,  3.00000000e+00, ...,
         0.00000000e+00,  4.00000000e+01,  0.00000000e+00],
       [-1.52541218e-03, -1.52541218e-03,  4.00000000e+00, ...,
         1.00000000e+00,  5.30000000e+01,  0.00000000e+00],
       [-3.02700997e-04, -3.02700997e-04,  2.00000000e+00, ...,
         0.00000000e+00,  3.30000000e+01,  0.00000000e+00]])

In [380]:
data_class = pd.read_csv('data/class.csv')

In [381]:
from sklearn.model_selection import train_test_split
start = datetime.datetime.now()
X_train, X_test, y_train, y_test = train_test_split(data_array, data_class, test_size=0.2, random_state=1)

In [389]:
from sklearn import linear_model
reg1 = linear_model.LinearRegression()
start = datetime.datetime.now()
reg1.fit(X_train, y_train)
end = datetime.datetime.now()
print  "Time taken: ", end - start
predict = reg1.predict(X_test)
print "RMSE: ", sqrt(mean_squared_error(y_test, predict))

Time taken:  0:00:00.025000
RMSE:  0.290914831709


In [390]:
from sklearn import linear_model
start = datetime.datetime.now()
reg2 = linear_model.Ridge(alpha = 1000.0)
reg2.fit (X_train, y_train) 
end = datetime.datetime.now()
print  "Time taken: ", end - start
predict1 = reg2.predict(X_test)
print "RMSE: ", sqrt(mean_squared_error(y_test, predict1))

Time taken:  0:00:00.007000
RMSE:  0.290890206628


In [391]:
from sklearn import linear_model
start = datetime.datetime.now()
reg3 = linear_model.LassoLars(alpha=0.01)
reg3.fit (X_train, y_train) 
end = datetime.datetime.now()
print  "Time taken: ", end - start
predict1 = reg3.predict(X_test)
print "RMSE: ", sqrt(mean_squared_error(y_test, predict1))

Time taken:  0:00:00.007000
RMSE:  0.290792519129


In [385]:
from xgboost.sklearn import XGBRegressor
start = datetime.datetime.now()
xgb = XGBRegressor()
xgb.fit(X_train,y_train)
end = datetime.datetime.now()
print  "Time taken: ", end - start
y_predict_xgb = xgb.predict(X_test)
print "RMSE: ", sqrt(mean_squared_error(y_test, y_predict_xgb))

Time taken:  0:00:04.148000
RMSE:  0.290544347787


In [386]:
import pickle
filename = 'xgboost.sav'
pickle.dump(xgb, open(filename, 'wb'))

In [387]:
from sklearn.cross_validation import cross_val_score, cross_val_score
def cross_validation_score(model,train,test):
    scores = cross_val_score(model, train, test, cv=10)
    return scores

In [393]:
scores = cross_validation_score(reg1, X_train, y_train)
scores

array([-0.00095185,  0.00086411, -0.00167071, -0.00084858,  0.00082369,
       -0.00056803, -0.00147359, -0.00378483, -0.00310475,  0.00025463])

In [395]:
scores = cross_validation_score(reg2, X_train, y_train)
scores

array([-0.00065642,  0.00117094, -0.00155971, -0.00013308,  0.000898  ,
       -0.00051441, -0.00153101, -0.00370618, -0.00298152,  0.00026095])

In [396]:
scores = cross_validation_score(reg3, X_train, y_train)
scores

array([-8.00971337e-05, -1.30256451e-04, -6.46520132e-04, -6.97172176e-05,
       -5.03698834e-05, -1.59462381e-03, -2.74390756e-03, -2.08069759e-03,
       -2.41532726e-03, -5.27172504e-04])

In [394]:
scores = cross_validation_score(xgb, X_train, y_train)
scores

array([-1.43852233e-04,  2.52961909e-06, -3.99940789e-03, -5.03836569e-05,
       -3.68995705e-03, -3.50745930e-03, -5.99285364e-03,  2.07218976e-03,
       -3.92313672e-03, -6.78124819e-03])

In [345]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(sample)

In [346]:
result

array([-0.5340421], dtype=float32)

In [374]:
value = (-result*(1299963.0-900001.0))+900001.0
value

array([1113597.5], dtype=float32)

In [263]:
def reverse_transformation(value, min_value, max_value):
    return (value*(max_value-min_value)+min_value) 