In [357]:
import pandas as pd
import numpy as np
import datetime
from sklearn.metrics import mean_squared_error
from math import sqrt

In [368]:
data=pd.read_csv("C:\Users\SAI SUPRAJA M\Documents\GitHub\HomeValuePrediction\data\preprocessed_data.csv", low_memory=False)

In [369]:
data.head()

lotsizesquarefeet  calculatedfinishedsquarefeet  bedroomcnt  bathroomcnt  \
0          -0.001201                     -0.001201         4.0          4.0   
1          -0.000301                     -0.000301         3.0          2.5   
2          -0.000412                     -0.000412         4.0          3.0   
3          -0.005995                     -0.005995         5.0          3.5   
4          -0.020725                     -0.020725         2.0          2.0   

   regionidzip  garagecarcnt  poolcnt  AgeofHouse  buildingclasstypeid  
0            0           0.0      0.0        67.0                  0.0  
1            1           2.0      0.0         3.0                  0.0  
2            2           2.0      0.0         3.0                  0.0  
3            3           1.0      0.0        57.0                  0.0  
4            3           2.0      0.0        37.0                  0.0

In [370]:
sample = [-0.001201,-0.001201,4.0,4.0,0,0.0,0.0,67.0,0.0]

In [371]:
data_array = data.values
data_array

array([[-1.20113718e-03, -1.20113718e-03,  4.00000000e+00, ...,
         0.00000000e+00,  6.70000000e+01,  0.00000000e+00],
       [-3.01403603e-04, -3.01403603e-04,  3.00000000e+00, ...,
         0.00000000e+00,  3.00000000e+00,  0.00000000e+00],
       [-4.11524515e-04, -4.11524515e-04,  4.00000000e+00, ...,
         0.00000000e+00,  3.00000000e+00,  0.00000000e+00],
       ...,
       [-3.09119688e-04, -3.09119688e-04,  3.00000000e+00, ...,
         0.00000000e+00,  5.00000000e+00,  0.00000000e+00],
       [-3.34554189e-04, -3.34554189e-04,  4.00000000e+00, ...,
         0.00000000e+00,  4.00000000e+00,  0.00000000e+00],
       [-5.00973941e-04, -5.00973941e-04,  4.00000000e+00, ...,
         0.00000000e+00,  3.00000000e+00,  0.00000000e+00]])

In [372]:
data_class = pd.read_csv('data/class.csv')

In [373]:
from sklearn.model_selection import train_test_split
start = datetime.datetime.now()
X_train, X_test, y_train, y_test = train_test_split(data_array, data_class, test_size=0.2, random_state=1)

In [364]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
start = datetime.datetime.now()
reg.fit(X_train, y_train)
end = datetime.datetime.now()
print  "Time taken: ", end - start
predict = reg.predict(X_test)
print "RMSE: ", sqrt(mean_squared_error(y_test, predict))

Time taken:  0:00:05.617000
RMSE:  0.290914831709


In [365]:
from sklearn import linear_model
start = datetime.datetime.now()
reg = linear_model.Ridge(alpha = 1000.0)
reg.fit (X_train, y_train) 
end = datetime.datetime.now()
print  "Time taken: ", end - start
predict1 = reg.predict(X_test)
print "RMSE: ", sqrt(mean_squared_error(y_test, predict1))

Time taken:  0:00:01.555000
RMSE:  0.290890206628


In [366]:
from sklearn import linear_model
start = datetime.datetime.now()
reg = linear_model.LassoLars(alpha=0.01)
reg.fit (X_train, y_train) 
end = datetime.datetime.now()
print  "Time taken: ", end - start
predict1 = reg.predict(X_test)
print "RMSE: ", sqrt(mean_squared_error(y_test, predict1))

Time taken:  0:00:00.771000
RMSE:  0.290792519129


In [367]:
from xgboost.sklearn import XGBRegressor
start = datetime.datetime.now()
xgb = XGBRegressor()
xgb.fit(X_train,y_train)
end = datetime.datetime.now()
print  "Time taken: ", end - start
y_predict_xgb = xgb.predict(X_test)
print "RMSE: ", sqrt(mean_squared_error(y_test, y_predict_xgb))

Time taken:  0:00:06.642000
RMSE:  0.290544347787


In [342]:
import pickle
filename = 'xgboost.sav'
pickle.dump(xgb, open(filename, 'wb'))

In [343]:
from sklearn.cross_validation import cross_val_score, cross_val_score
def cross_validation_score(model,train,test):
    scores = cross_val_score(model, train, test, cv=10)
    return scores

In [344]:
scores = cross_validation_score(xgb, X_test, y_test)

In [345]:
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(sample)

In [346]:
result

array([-0.5340421], dtype=float32)

In [374]:
value = (-result*(1299963.0-900001.0))+900001.0
value

array([1113597.5], dtype=float32)

In [263]:
def reverse_transformation(value, min_value, max_value):
    return (value*(max_value-min_value)+min_value) 